# YNAB API
# https://api.ynab.com/v1

### Get all budgets
GET https://api.ynab.com/v1/budgets
Accept: application/json
Authorization: Bearer {{ynab_token}}


### Get all accounts for a budget
GET https://api.ynab.com/v1/budgets/{{ynab_budget_id}}/accounts
Accept: application/json
Authorization: Bearer {{ynab_token}}


### Get categories for a budget
GET https://api.ynab.com/v1/budgets/{{ynab_budget_id}}/categories
Accept: application/json
Authorization: Bearer {{ynab_token}}


### Get payees for a budget
GET https://api.ynab.com/v1/budgets/{{ynab_budget_id}}/payees
Accept: application/json
Authorization: Bearer {{ynab_token}}
