# YNAB API
# https://api.ynab.com
# https://api.ynab.com/v1

### Get all budgets
GET https://api.ynab.com/v1/budgets
accept: application/json
Authorization: Bearer

### Get all accounts for a budget
GET https://api.ynab.com/v1/budgets/a50d8392-9abe-4827-b941-b311de6fdbd8/accounts
accept: application/json
Authorization: Bearer {{pat}}

### Get categories
GET https://api.ynab.com/v1/budgets
accept: application/json
Authorization: Bearer

